/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('vexip-ui')['Avatar']
    Badge: typeof import('vexip-ui')['Badge']
    BaseCard: typeof import('./src/components/BaseCard.vue')['default']
    Button: typeof import('vexip-ui')['Button']
    Dropdown: typeof import('vexip-ui')['Dropdown']
    DropdownItem: typeof import('vexip-ui')['DropdownItem']
    DropdownList: typeof import('vexip-ui')['DropdownList']
    Form: typeof import('vexip-ui')['Form']
    FormItem: typeof import('vexip-ui')['FormItem']
    FormSubmit: typeof import('vexip-ui')['FormSubmit']
    Icon: typeof import('vexip-ui')['Icon']
    Input: typeof import('vexip-ui')['Input']
    Leaderboard: typeof import('./src/components/Leaderboard/index.vue')['default']
    Menu: typeof import('vexip-ui')['Menu']
    MenuItem: typeof import('vexip-ui')['MenuItem']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Space: typeof import('vexip-ui')['Space']
    Table: typeof import('vexip-ui')['Table']
    TableColumn: typeof import('vexip-ui')['TableColumn']
    TabNav: typeof import('vexip-ui')['TabNav']
    TabNavItem: typeof import('vexip-ui')['TabNavItem']
  }
}
